// countries.js
// Full list of countries with ISO codes and currencies (as of 2025/2026)
// You can place this file in the same folder as your HTML files

export const countries = [
    { code: "af", name: "Afghanistan", currency: "Afghan Afghani (AFN ؋)" },
    { code: "al", name: "Albania", currency: "Albanian Lek (ALL L)" },
    { code: "dz", name: "Algeria", currency: "Algerian Dinar (DZD د.ج)" },
    { code: "as", name: "American Samoa", currency: "US Dollar (USD $)" },
    { code: "ad", name: "Andorra", currency: "Euro (EUR €)" },
    { code: "ao", name: "Angola", currency: "Angolan Kwanza (AOA Kz)" },
    { code: "ai", name: "Anguilla", currency: "East Caribbean Dollar (XCD $)" },
    { code: "ag", name: "Antigua and Barbuda", currency: "East Caribbean Dollar (XCD $)" },
    { code: "ar", name: "Argentina", currency: "Argentine Peso (ARS $)" },
    { code: "am", name: "Armenia", currency: "Armenian Dram (AMD ֏)" },
    { code: "aw", name: "Aruba", currency: "Aruban Florin (AWG ƒ)" },
    { code: "au", name: "Australia", currency: "Australian Dollar (AUD $)" },
    { code: "at", name: "Austria", currency: "Euro (EUR €)" },
    { code: "az", name: "Azerbaijan", currency: "Azerbaijani Manat (AZN ₼)" },
    { code: "bs", name: "Bahamas", currency: "Bahamian Dollar (BSD $)" },
    { code: "bh", name: "Bahrain", currency: "Bahraini Dinar (BHD .د.ب)" },
    { code: "bd", name: "Bangladesh", currency: "Bangladeshi Taka (BDT ৳)" },
    { code: "bb", name: "Barbados", currency: "Barbadian Dollar (BBD $)" },
    { code: "by", name: "Belarus", currency: "Belarusian Ruble (BYN Br)" },
    { code: "be", name: "Belgium", currency: "Euro (EUR €)" },
    { code: "bz", name: "Belize", currency: "Belize Dollar (BZD BZ$)" },
    { code: "bj", name: "Benin", currency: "West African CFA Franc (XOF CFA)" },
    { code: "bm", name: "Bermuda", currency: "Bermudian Dollar (BMD $)" },
    { code: "bt", name: "Bhutan", currency: "Bhutanese Ngultrum (BTN Nu.) / Indian Rupee (INR ₹)" },
    { code: "bo", name: "Bolivia", currency: "Bolivian Boliviano (BOB Bs.)" },
    { code: "ba", name: "Bosnia and Herzegovina", currency: "Bosnia and Herzegovina Convertible Mark (BAM KM)" },
    { code: "bw", name: "Botswana", currency: "Botswana Pula (BWP P)" },
    { code: "br", name: "Brazil", currency: "Brazilian Real (BRL R$)" },
    { code: "io", name: "British Indian Ocean Territory", currency: "US Dollar (USD $)" },
    { code: "bn", name: "Brunei", currency: "Brunei Dollar (BND $)" },
    { code: "bg", name: "Bulgaria", currency: "Bulgarian Lev (BGN лв)" },
    { code: "bf", name: "Burkina Faso", currency: "West African CFA Franc (XOF CFA)" },
    { code: "bi", name: "Burundi", currency: "Burundian Franc (BIF Fr)" },
    { code: "cv", name: "Cabo Verde", currency: "Cape Verdean Escudo (CVE $)" },
    { code: "kh", name: "Cambodia", currency: "Cambodian Riel (KHR ៛)" },
    { code: "cm", name: "Cameroon", currency: "Central African CFA Franc (XAF FCFA)" },
    { code: "ca", name: "Canada", currency: "Canadian Dollar (CAD $)" },
    { code: "ky", name: "Cayman Islands", currency: "Cayman Islands Dollar (KYD $)" },
    { code: "cf", name: "Central African Republic", currency: "Central African CFA Franc (XAF FCFA)" },
    { code: "td", name: "Chad", currency: "Central African CFA Franc (XAF FCFA)" },
    { code: "cl", name: "Chile", currency: "Chilean Peso (CLP $)" },
    { code: "cn", name: "China", currency: "Chinese Yuan (CNY ¥)" },
    { code: "co", name: "Colombia", currency: "Colombian Peso (COP $)" },
    { code: "km", name: "Comoros", currency: "Comorian Franc (KMF CF)" },
    { code: "cg", name: "Congo", currency: "Central African CFA Franc (XAF FCFA)" },
    { code: "cd", name: "Congo (DRC)", currency: "Congolese Franc (CDF Fr)" },
    { code: "ck", name: "Cook Islands", currency: "New Zealand Dollar (NZD $)" },
    { code: "cr", name: "Costa Rica", currency: "Costa Rican Colón (CRC ₡)" },
    { code: "hr", name: "Croatia", currency: "Euro (EUR €)" },
    { code: "cu", name: "Cuba", currency: "Cuban Peso (CUP $)" },
    { code: "cw", name: "Curaçao", currency: "Netherlands Antillean Guilder (ANG ƒ)" },
    { code: "cy", name: "Cyprus", currency: "Euro (EUR €)" },
    { code: "cz", name: "Czech Republic", currency: "Czech Koruna (CZK Kč)" },
    { code: "dk", name: "Denmark", currency: "Danish Krone (DKK kr)" },
    { code: "dj", name: "Djibouti", currency: "Djiboutian Franc (DJF Fdj)" },
    { code: "dm", name: "Dominica", currency: "East Caribbean Dollar (XCD $)" },
    { code: "do", name: "Dominican Republic", currency: "Dominican Peso (DOP $)" },
    { code: "ec", name: "Ecuador", currency: "US Dollar (USD $)" },
    { code: "eg", name: "Egypt", currency: "Egyptian Pound (EGP ج.م)" },
    { code: "sv", name: "El Salvador", currency: "US Dollar (USD $)" },
    { code: "gq", name: "Equatorial Guinea", currency: "Central African CFA Franc (XAF FCFA)" },
    { code: "er", name: "Eritrea", currency: "Eritrean Nakfa (ERN Nfk)" },
    { code: "ee", name: "Estonia", currency: "Euro (EUR €)" },
    { code: "sz", name: "Eswatini", currency: "Swazi Lilangeni (SZL L) / South African Rand (ZAR R)" },
    { code: "et", name: "Ethiopia", currency: "Ethiopian Birr (ETB Br)" },
    { code: "fk", name: "Falkland Islands", currency: "Falkland Islands Pound (£)" },
    { code: "fo", name: "Faroe Islands", currency: "Danish Krone (DKK kr)" },
    { code: "fj", name: "Fiji", currency: "Fijian Dollar (FJD $)" },
    { code: "fi", name: "Finland", currency: "Euro (EUR €)" },
    { code: "fr", name: "France", currency: "Euro (EUR €)" },
    { code: "gf", name: "French Guiana", currency: "Euro (EUR €)" },
    { code: "pf", name: "French Polynesia", currency: "CFP Franc (XPF ₣)" },
    { code: "ga", name: "Gabon", currency: "Central African CFA Franc (XAF FCFA)" },
    { code: "gm", name: "Gambia", currency: "Gambian Dalasi (GMD D)" },
    { code: "ge", name: "Georgia", currency: "Georgian Lari (GEL ₾)" },
    { code: "de", name: "Germany", currency: "Euro (EUR €)" },
    { code: "gh", name: "Ghana", currency: "Ghanaian Cedi (GHS ₵)" },
    { code: "gi", name: "Gibraltar", currency: "Gibraltar Pound (£)" },
    { code: "gr", name: "Greece", currency: "Euro (EUR €)" },
    { code: "gl", name: "Greenland", currency: "Danish Krone (DKK kr)" },
    { code: "gd", name: "Grenada", currency: "East Caribbean Dollar (XCD $)" },
    { code: "gp", name: "Guadeloupe", currency: "Euro (EUR €)" },
    { code: "gu", name: "Guam", currency: "US Dollar (USD $)" },
    { code: "gt", name: "Guatemala", currency: "Guatemalan Quetzal (GTQ Q)" },
    { code: "gg", name: "Guernsey", currency: "Guernsey Pound (£) / Pound Sterling (£)" },
    { code: "gn", name: "Guinea", currency: "Guinean Franc (GNF Fr)" },
    { code: "gw", name: "Guinea-Bissau", currency: "West African CFA Franc (XOF CFA)" },
    { code: "gy", name: "Guyana", currency: "Guyanese Dollar (GYD $)" },
    { code: "ht", name: "Haiti", currency: "Haitian Gourde (HTG G)" },
    { code: "hn", name: "Honduras", currency: "Honduran Lempira (HNL L)" },
    { code: "hk", name: "Hong Kong", currency: "Hong Kong Dollar (HKD $)" },
    { code: "hu", name: "Hungary", currency: "Hungarian Forint (HUF Ft)" },
    { code: "is", name: "Iceland", currency: "Icelandic Króna (ISK kr)" },
    { code: "in", name: "India", currency: "Indian Rupee (INR ₹)" },
    { code: "id", name: "Indonesia", currency: "Indonesian Rupiah (IDR Rp)" },
    { code: "ir", name: "Iran", currency: "Iranian Rial (IRR ﷼)" },
    { code: "iq", name: "Iraq", currency: "Iraqi Dinar (IQD ع.د)" },
    { code: "ie", name: "Ireland", currency: "Euro (EUR €)" },
    { code: "im", name: "Isle of Man", currency: "Manx Pound (£) / Pound Sterling (£)" },
    { code: "il", name: "Israel", currency: "Israeli New Shekel (ILS ₪)" },
    { code: "it", name: "Italy", currency: "Euro (EUR €)" },
    { code: "ci", name: "Ivory Coast", currency: "West African CFA Franc (XOF CFA)" },
    { code: "jm", name: "Jamaica", currency: "Jamaican Dollar (JMD $)" },
    { code: "jp", name: "Japan", currency: "Japanese Yen (JPY ¥)" },
    { code: "je", name: "Jersey", currency: "Jersey Pound (£) / Pound Sterling (£)" },
    { code: "jo", name: "Jordan", currency: "Jordanian Dinar (JOD د.ا)" },
    { code: "kz", name: "Kazakhstan", currency: "Kazakhstani Tenge (KZT ₸)" },
    { code: "ke", name: "Kenya", currency: "Kenyan Shilling (KES Sh)" },
    { code: "ki", name: "Kiribati", currency: "Australian Dollar (AUD $)" },
    { code: "kp", name: "Korea (North)", currency: "North Korean Won (KPW ₩)" },
    { code: "kr", name: "Korea (South)", currency: "South Korean Won (KRW ₩)" },
    { code: "kw", name: "Kuwait", currency: "Kuwaiti Dinar (KWD د.ك)" },
    { code: "kg", name: "Kyrgyzstan", currency: "Kyrgyzstani Som (KGS с)" },
    { code: "la", name: "Laos", currency: "Lao Kip (LAK ₭)" },
    { code: "lv", name: "Latvia", currency: "Euro (EUR €)" },
    { code: "lb", name: "Lebanon", currency: "Lebanese Pound (LBP ل.ل)" },
    { code: "ls", name: "Lesotho", currency: "Lesotho Loti (LSL L) / South African Rand (ZAR R)" },
    { code: "lr", name: "Liberia", currency: "Liberian Dollar (LRD $)" },
    { code: "ly", name: "Libya", currency: "Libyan Dinar (LYD ل.د)" },
    { code: "li", name: "Liechtenstein", currency: "Swiss Franc (CHF Fr)" },
    { code: "lt", name: "Lithuania", currency: "Euro (EUR €)" },
    { code: "lu", name: "Luxembourg", currency: "Euro (EUR €)" },
    { code: "mo", name: "Macao", currency: "Macanese Pataca (MOP P)" },
    { code: "mg", name: "Madagascar", currency: "Malagasy Ariary (MGA Ar)" },
    { code: "mw", name: "Malawi", currency: "Malawian Kwacha (MWK MK)" },
    { code: "my", name: "Malaysia", currency: "Malaysian Ringgit (MYR RM)" },
    { code: "mv", name: "Maldives", currency: "Maldivian Rufiyaa (MVR .ރ)" },
    { code: "ml", name: "Mali", currency: "West African CFA Franc (XOF CFA)" },
    { code: "mt", name: "Malta", currency: "Euro (EUR €)" },
    { code: "mh", name: "Marshall Islands", currency: "US Dollar (USD $)" },
    { code: "mq", name: "Martinique", currency: "Euro (EUR €)" },
    { code: "mr", name: "Mauritania", currency: "Mauritanian Ouguiya (MRU UM)" },
    { code: "mu", name: "Mauritius", currency: "Mauritian Rupee (MUR ₨)" },
    { code: "yt", name: "Mayotte", currency: "Euro (EUR €)" },
    { code: "mx", name: "Mexico", currency: "Mexican Peso (MXN $)" },
    { code: "fm", name: "Micronesia", currency: "US Dollar (USD $)" },
    { code: "md", name: "Moldova", currency: "Moldovan Leu (MDL L)" },
    { code: "mc", name: "Monaco", currency: "Euro (EUR €)" },
    { code: "mn", name: "Mongolia", currency: "Mongolian Tögrög (MNT ₮)" },
    { code: "me", name: "Montenegro", currency: "Euro (EUR €)" },
    { code: "ms", name: "Montserrat", currency: "East Caribbean Dollar (XCD $)" },
    { code: "ma", name: "Morocco", currency: "Moroccan Dirham (MAD د.م.)" },
    { code: "mz", name: "Mozambique", currency: "Mozambican Metical (MZN MT)" },
    { code: "mm", name: "Myanmar", currency: "Myanmar Kyat (MMK K)" },
    { code: "na", name: "Namibia", currency: "Namibian Dollar (NAD $) / South African Rand (ZAR R)" },
    { code: "nr", name: "Nauru", currency: "Australian Dollar (AUD $)" },
    { code: "np", name: "Nepal", currency: "Nepalese Rupee (NPR ₨)" },
    { code: "nl", name: "Netherlands", currency: "Euro (EUR €)" },
    { code: "nc", name: "New Caledonia", currency: "CFP Franc (XPF ₣)" },
    { code: "nz", name: "New Zealand", currency: "New Zealand Dollar (NZD $)" },
    { code: "ni", name: "Nicaragua", currency: "Nicaraguan Córdoba (NIO C$)" },
    { code: "ne", name: "Niger", currency: "West African CFA Franc (XOF CFA)" },
    { code: "ng", name: "Nigeria", currency: "Nigerian Naira (NGN ₦)" },
    { code: "nu", name: "Niue", currency: "New Zealand Dollar (NZD $)" },
    { code: "nf", name: "Norfolk Island", currency: "Australian Dollar (AUD $)" },
    { code: "mk", name: "North Macedonia", currency: "Macedonian Denar (MKD ден)" },
    { code: "mp", name: "Northern Mariana Islands", currency: "US Dollar (USD $)" },
    { code: "no", name: "Norway", currency: "Norwegian Krone (NOK kr)" },
    { code: "om", name: "Oman", currency: "Omani Rial (OMR ر.ع.)" },
    { code: "pk", name: "Pakistan", currency: "Pakistani Rupee (PKR ₨)" },
    { code: "pw", name: "Palau", currency: "US Dollar (USD $)" },
    { code: "ps", name: "Palestine", currency: "Israeli New Shekel (ILS ₪) / Jordanian Dinar (JOD د.ا)" },
    { code: "pa", name: "Panama", currency: "Panamanian Balboa (PAB B/.) / US Dollar (USD $)" },
    { code: "pg", name: "Papua New Guinea", currency: "Papua New Guinean Kina (PGK K)" },
    { code: "py", name: "Paraguay", currency: "Paraguayan Guarani (PYG ₲)" },
    { code: "pe", name: "Peru", currency: "Peruvian Sol (PEN S/)" },
    { code: "ph", name: "Philippines", currency: "Philippine Peso (PHP ₱)" },
    { code: "pl", name: "Poland", currency: "Polish Złoty (PLN zł)" },
    { code: "pt", name: "Portugal", currency: "Euro (EUR €)" },
    { code: "pr", name: "Puerto Rico", currency: "US Dollar (USD $)" },
    { code: "qa", name: "Qatar", currency: "Qatari Riyal (QAR ر.ق)" },
    { code: "re", name: "Réunion", currency: "Euro (EUR €)" },
    { code: "ro", name: "Romania", currency: "Romanian Leu (RON L)" },
    { code: "ru", name: "Russia", currency: "Russian Ruble (RUB ₽)" },
    { code: "rw", name: "Rwanda", currency: "Rwandan Franc (RWF FRw)" },
    { code: "bl", name: "Saint Barthélemy", currency: "Euro (EUR €)" },
    { code: "sh", name: "Saint Helena", currency: "Saint Helena Pound (£)" },
    { code: "kn", name: "Saint Kitts and Nevis", currency: "East Caribbean Dollar (XCD $)" },
    { code: "lc", name: "Saint Lucia", currency: "East Caribbean Dollar (XCD $)" },
    { code: "mf", name: "Saint Martin", currency: "Euro (EUR €)" },
    { code: "pm", name: "Saint Pierre and Miquelon", currency: "Euro (EUR €)" },
    { code: "vc", name: "Saint Vincent and the Grenadines", currency: "East Caribbean Dollar (XCD $)" },
    { code: "ws", name: "Samoa", currency: "Samoan Tālā (WST T)" },
    { code: "sm", name: "San Marino", currency: "Euro (EUR €)" },
    { code: "st", name: "São Tomé and Príncipe", currency: "São Tomé and Príncipe Dobra (STN Db)" },
    { code: "sa", name: "Saudi Arabia", currency: "Saudi Riyal (SAR ر.س)" },
    { code: "sn", name: "Senegal", currency: "West African CFA Franc (XOF CFA)" },
    { code: "rs", name: "Serbia", currency: "Serbian Dinar (RSD дин)" },
    { code: "sc", name: "Seychelles", currency: "Seychellois Rupee (SCR ₨)" },
    { code: "sl", name: "Sierra Leone", currency: "Sierra Leonean Leone (SLL Le)" },
    { code: "sg", name: "Singapore", currency: "Singapore Dollar (SGD $)" },
    { code: "sx", name: "Sint Maarten", currency: "Netherlands Antillean Guilder (ANG ƒ)" },
    { code: "sk", name: "Slovakia", currency: "Euro (EUR €)" },
    { code: "si", name: "Slovenia", currency: "Euro (EUR €)" },
    { code: "sb", name: "Solomon Islands", currency: "Solomon Islands Dollar (SBD $)" },
    { code: "so", name: "Somalia", currency: "Somali Shilling (SOS Sh)" },
    { code: "za", name: "South Africa", currency: "South African Rand (ZAR R)" },
    { code: "gs", name: "South Georgia and the South Sandwich Islands", currency: "No universal currency" },
    { code: "ss", name: "South Sudan", currency: "South Sudanese Pound (SSP £)" },
    { code: "es", name: "Spain", currency: "Euro (EUR €)" },
    { code: "lk", name: "Sri Lanka", currency: "Sri Lankan Rupee (LKR ₨)" },
    { code: "sd", name: "Sudan", currency: "Sudanese Pound (SDG ج.س.)" },
    { code: "sr", name: "Suriname", currency: "Surinamese Dollar (SRD $)" },
    { code: "sj", name: "Svalbard and Jan Mayen", currency: "Norwegian Krone (NOK kr)" },
    { code: "se", name: "Sweden", currency: "Swedish Krona (SEK kr)" },
    { code: "ch", name: "Switzerland", currency: "Swiss Franc (CHF Fr)" },
    { code: "sy", name: "Syria", currency: "Syrian Pound (SYP £)" },
    { code: "tw", name: "Taiwan", currency: "New Taiwan Dollar (TWD NT$)" },
    { code: "tj", name: "Tajikistan", currency: "Tajikistani Somoni (TJS ЅМ)" },
    { code: "tz", name: "Tanzania", currency: "Tanzanian Shilling (TZS Sh)" },
    { code: "th", name: "Thailand", currency: "Thai Baht (THB ฿)" },
    { code: "tl", name: "Timor-Leste", currency: "US Dollar (USD $)" },
    { code: "tg", name: "Togo", currency: "West African CFA Franc (XOF CFA)" },
    { code: "tk", name: "Tokelau", currency: "New Zealand Dollar (NZD $)" },
    { code: "to", name: "Tonga", currency: "Tongan Paʻanga (TOP T$)" },
    { code: "tt", name: "Trinidad and Tobago", currency: "Trinidad and Tobago Dollar (TTD $)" },
    { code: "tn", name: "Tunisia", currency: "Tunisian Dinar (TND د.ت)" },
    { code: "tr", name: "Turkey", currency: "Turkish Lira (TRY ₺)" },
    { code: "tm", name: "Turkmenistan", currency: "Turkmenistani Manat (TMT m)" },
    { code: "tc", name: "Turks and Caicos Islands", currency: "US Dollar (USD $)" },
    { code: "tv", name: "Tuvalu", currency: "Australian Dollar (AUD $)" },
    { code: "ug", name: "Uganda", currency: "Ugandan Shilling (UGX Sh)" },
    { code: "ua", name: "Ukraine", currency: "Ukrainian Hryvnia (UAH ₴)" },
    { code: "ae", name: "United Arab Emirates", currency: "UAE Dirham (AED د.إ)" },
    { code: "gb", name: "United Kingdom", currency: "Pound Sterling (GBP £)" },
    { code: "us", name: "United States", currency: "US Dollar (USD $)" },
    { code: "uy", name: "Uruguay", currency: "Uruguayan Peso (UYU $)" },
    { code: "uz", name: "Uzbekistan", currency: "Uzbekistani So'm (UZS so'm)" },
    { code: "vu", name: "Vanuatu", currency: "Vanuatu Vatu (VUV VT)" },
    { code: "va", name: "Vatican City", currency: "Euro (EUR €)" },
    { code: "ve", name: "Venezuela", currency: "Venezuelan Bolívar (VES Bs.)" },
    { code: "vn", name: "Vietnam", currency: "Vietnamese Đồng (VND ₫)" },
    { code: "vg", name: "Virgin Islands (British)", currency: "US Dollar (USD $)" },
    { code: "vi", name: "Virgin Islands (US)", currency: "US Dollar (USD $)" },
    { code: "wf", name: "Wallis and Futuna", currency: "CFP Franc (XPF ₣)" },
    { code: "eh", name: "Western Sahara", currency: "Moroccan Dirham (MAD د.م.)" },
    { code: "ye", name: "Yemen", currency: "Yemeni Rial (YER ﷼)" },
    { code: "zm", name: "Zambia", currency: "Zambian Kwacha (ZMW K)" },
    { code: "zw", name: "Zimbabwe", currency: "Zimbabwean Dollar (ZWL $)" }
  ];